from snakemake.utils import min_version


min_version("6.10.0")


configfile: "config/config.yaml"


# declare https://github.com/ntnn19/AlphaFold3_workflow as a module
module AlphaFold3_workflow:
    snakefile: 
        github("ntnn19/AlphaFold3_workflow", path="workflow/Snakefile", branch="dev")
    config:
        config


# use all rules from https://github.com/ntnn19/AlphaFold3_workflow
use rule * from AlphaFold3_workflow
