#!/bin/bash
#python workflow/scripts/prepare_workflow.py .test/config/custom/config.yaml -o .test/config/custom && snakemake test_custom/rule_PREPROCESSING --configfile .test/config/custom/config.yaml --directory .test/config/custom --use-singularity --singularity-args '--nv -B /gpfs/cssb/group/cssb-topf/natan/af3db:/root/public_databases -B tmp:/tmp -B /gpfs/cssb/group/cssb-topf/natan/singularity_containers/alphafold3/weights:/root/models -B results:/root/af_output' -p --workflow-profile profiles/profile -j 10
#python workflow/scripts/prepare_workflow.py .test/config/custom/config.yaml -o .test/config/custom && snakemake --configfile .test/config/custom/config.yaml --directory .test/config/custom --use-singularity --singularity-args '--nv -B /gpfs/cssb/group/cssb-topf/natan/af3db:/root/public_databases -B tmp:/tmp -B /gpfs/cssb/group/cssb-topf/natan/singularity_containers/alphafold3/weights:/root/models -B results:/root/af_output' -p --workflow-profile profiles/profile -j 10 -n
#python workflow/scripts/prepare_workflow.py .test/config/custom_template/config.yaml -o .test/config/custom_template && snakemake results/rule_PREPROCESSING --configfile .test/config/custom_template/config.yaml --directory .test/config/custom_template --use-singularity --singularity-args '--nv -B /gpfs/cssb/group/cssb-topf/natan/af3db:/root/public_databases -B tmp:/tmp -B /gpfs/cssb/group/cssb-topf/natan/singularity_containers/alphafold3/weights:/root/models -B results:/root/af_output' -p --workflow-profile profiles/profile -j 10
#python workflow/scripts/prepare_workflow.py .test/config/custom_template/config.yaml -o .test/config/custom_template && snakemake --configfile .test/config/custom_template/config.yaml --directory .test/config/custom_template --use-singularity --singularity-args '--nv -B /gpfs/cssb/group/cssb-topf/natan/af3db:/root/public_databases -B tmp:/tmp -B /gpfs/cssb/group/cssb-topf/natan/singularity_containers/alphafold3/weights:/root/models -B results:/root/af_output' -p --workflow-profile profiles/profile -j 10 -n
python workflow/scripts/prepare_workflow.py .test/config/custom_ground_truth/config.yaml -o .test/config/custom_ground_truth && snakemake results/rule_PREPROCESSING --configfile .test/config/custom_ground_truth/config.yaml --directory .test/config/custom_ground_truth --use-singularity --singularity-args '--nv -B /gpfs/cssb/group/cssb-topf/natan/af3db:/root/public_databases -B tmp:/tmp -B /gpfs/cssb/group/cssb-topf/natan/singularity_containers/alphafold3/weights:/root/models -B results:/root/af_output' -p --workflow-profile profiles/profile -j 10
python workflow/scripts/prepare_workflow.py .test/config/custom_ground_truth/config.yaml -o .test/config/custom_ground_truth && snakemake --configfile .test/config/custom_ground_truth/config.yaml --directory .test/config/custom_ground_truth --use-singularity --singularity-args '--nv -B /gpfs/cssb/group/cssb-topf/natan/af3db:/root/public_databases -B tmp:/tmp -B /gpfs/cssb/group/cssb-topf/natan/singularity_containers/alphafold3/weights:/root/models -B results:/root/af_output' -p --workflow-profile profiles/profile -j 10 -n
#python workflow/scripts/prepare_workflow.py .test/config/pulldown/config.yaml -o .test/config/pulldown && snakemake --configfile .test/config/pulldown/config.yaml --directory .test/config/pulldown --use-singularity --singularity-args '--nv -B /gpfs/cssb/group/cssb-topf/natan/af3db:/root/public_databases -B tmp:/tmp -B /gpfs/cssb/group/cssb-topf/natan/singularity_containers/alphafold3/weights:/root/models -B results:/root/af_output' -p --workflow-profile profiles/profile -j 500
#python workflow/scripts/prepare_workflow.py .test/config/entry_points/data_pipeline_ready/config.yaml -o .test/config/entry_points/data_pipeline_ready && snakemake --configfile .test/config/entry_points/data_pipeline_ready/config.yaml --directory .test/config/entry_points/data_pipeline_ready --use-singularity --singularity-args '--nv -B /gpfs/cssb/group/cssb-topf/natan/af3db:/root/public_databases -B tmp:/tmp -B /gpfs/cssb/group/cssb-topf/natan/singularity_containers/alphafold3/weights:/root/models -B results:/root/af_output' -p --workflow-profile profiles/profile -j 10
#python workflow/scripts/prepare_workflow.py .test/config/entry_points/data_pipeline_ready_plus_raw_data/config.yaml -o .test/config/entry_points/data_pipeline_ready_plus_raw_data && snakemake --configfile .test/config/entry_points/data_pipeline_ready_plus_raw_data/config.yaml --directory .test/config/entry_points/data_pipeline_ready_plus_raw_data --use-singularity --singularity-args '--nv -B /gpfs/cssb/group/cssb-topf/natan/af3db:/root/public_databases -B tmp:/tmp -B /gpfs/cssb/group/cssb-topf/natan/singularity_containers/alphafold3/weights:/root/models -B results:/root/af_output' -p --workflow-profile profiles/profile -j 10
#python workflow/scripts/prepare_workflow.py .test/config/entry_points/inference_ready/config.yaml -o .test/config/entry_points/inference_ready && snakemake --configfile .test/config/entry_points/inference_ready/config.yaml --directory .test/config/entry_points/inference_ready --use-singularity --singularity-args '--nv -B /gpfs/cssb/group/cssb-topf/natan/af3db:/root/public_databases -B tmp:/tmp -B /gpfs/cssb/group/cssb-topf/natan/singularity_containers/alphafold3/weights:/root/models -B results:/root/af_output' -p --workflow-profile profiles/profile -j 10
