executor: local
cores: 1
use-singularity: true
use-conda: true
conda-frontend: mamba # or micromamba
singularity-args: "--nv"
printshellcmds: true
keep-going: false
rerun-incomplete: true
rerun-triggers: mtime
latency-wait: 60
envvars: [APPTAINER_BINDPATH, SINGULARITY_BINDPATH, APPTAINER_NV, SINGULARITY_NV]
set-resources:
    AF3_INFERENCE:
        mem_mb: 200000
