rule MERGE_MONO_AND_MULTI_JSON:
    input:
        unpack(get_merge_inputs)
    log:
        os.path.join(OUTPUT_DIR, "logs", "rule_MERGE_MONOMERS_TO_MULTIMERS", "{multi}.log"),
    benchmark:
        os.path.join(OUTPUT_DIR, "benchmarks", "rule_MERGE_MONOMERS_TO_MULTIMERS", "{multi}.tsv"),
    resources:
        mem_mb  = 2000,
        runtime = 10,
    params:
        _helper = f"{WORKFLOW_DIR}/scripts/merge_mono_and_multi_jsons.py",
        # TODO: for entrypoint mode compatibility, the user provided map should be appended to the one generated by the workflow
        chain_map = f"{OUTPUT_DIR}/rule_PREPROCESSING/metadata/inference_to_data_pipeline_map.tsv" if DATA_PIPELINE_READY_DF.empty else f"{NORMALIZED_INPUTS_DIR}/inference_to_data_pipeline_map.tsv"
    output:
        os.path.join(OUTPUT_DIR,"rule_MERGE_MONOMERS_TO_MULTIMERS","{multi}_data.json") if MODE in ["custom","all-vs-all","pulldown","virtual-drug-screen","stoichio-screen"] else [],
    conda: "../envs/preprocessing.yaml"
    shell:
        """
        python {params._helper} {input} {output} {params.chain_map} \
        2>&1 | tee {log}
        """
