sample_sheets:
  merge_ready: merge_ready_samples.tsv
  data_pipeline_ready: data_pipeline_ready_samples.tsv
  raw_data: raw_data.tsv
mode: custom
msa_option: none
n_splits: 1
af3_flags:
  af3_container: /tmp/af3.sif
  models_dir: /tmp/af3_models
  databases_dir: /tmp/af3_db
output_dir: results
run_data_pipeline_locally: true
exclusive_lock: false
